apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 02204e08-f0a2-4b8a-b86e-ce52508150e2
    run.googleapis.com/build-image-uri: asia-south1-docker.pkg.dev/careerpath-469205/cloud-run-source-deploy/pathpilot
    run.googleapis.com/build-name: projects/412871071473/locations/asia-south1/builds/02204e08-f0a2-4b8a-b86e-ce52508150e2
    run.googleapis.com/build-source-location: gs://run-sources-careerpath-469205-asia-south1/services/pathpilot/1755748742.5953-83b4f1c23d6a40d6a94a864c869506f0.zip#1755748756441032
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://pathpilot-412871071473.asia-south1.run.app","https://pathpilot-c4tbbx3f7a-el.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-south1
    run.googleapis.com/satisfiesPzs: 'true'
  name: pathpilot
  namespace: '412871071473'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: careerpath-469205:us-central1:fraud-detection-db
        run.googleapis.com/network-interfaces: '[{"network":"appie","subnetwork":"appie"}]'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/vpc-access-egress: all-traffic
      labels:
        client.knative.dev/nonce: 7c5a2680-1b90-42ca-898f-523e47a741a9
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: asia-south1-docker.pkg.dev/careerpath-469205/cloud-run-source-deploy/pathpilot@sha256:06c68edcb267c110415d61f90a2e05e0321f0dc9adfbd1da02806be5b78a4872
        name: pathpilot-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 412871071473-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
