# Generated by Django 5.2.4 on 2025-08-20 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('company_profile', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('telecommuting', models.BooleanField(default=False)),
                ('has_company_logo', models.BooleanField(default=False)),
                ('has_questions', models.BooleanField(default=False)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('required_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('required_education', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fraudulent', models.BooleanField()),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fraud_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sentiment_score', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_prediction', to='app.jobposting')),
            ],
            options={
                'db_table': 'fraud_predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
