# Generated by Django 5.2.4 on 2025-08-21 06:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dataqualitymetrics_modelperformance_predictionbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudprediction',
            name='ai_generation_score',
            field=models.FloatField(default=0.0, help_text='Probability of AI-generated content (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='fraudprediction',
            name='embedding_similarity',
            field=models.FloatField(default=0.0, help_text='Similarity to known fraud patterns (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddIndex(
            model_name='fraudprediction',
            index=models.Index(fields=['ai_generation_score'], name='fraud_predi_ai_gene_c48db9_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudprediction',
            index=models.Index(fields=['embedding_similarity'], name='fraud_predi_embeddi_8a7aa3_idx'),
        ),
    ]
