# Generated by Django 5.2.4 on 2025-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fraudprediction_ai_generation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudprediction',
            name='ai_analysis_details',
            field=models.JSONField(blank=True, default=dict, help_text='Raw details from AI analysis (e.g., Gemini prompts and responses)'),
        ),
    ]
